parameters:
#    min_sal_sid_pla_users.example.class: MinSal\SidPla\UsersBundle\Example

services:
    sidpla_user.registration.form.type:
        class: MinSal\SidPla\UsersBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sidpla_user_registration }
            
    sidpla_user.form.handler.registration:
        class: MinSal\SidPla\UsersBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@service_container"]
        scope: request
        public: false