#****************************
#*** Inventario Detallado ***
#****************************
MinSalSCAProcesosBundle_mantInventariosDet:
    pattern:  /inventario/mantInventariosDet
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantInventariosDet } 
    
MinSalSCAProcesosBundle_consultarInventariosDetJSON:
    pattern:  /inventario/consultarInventariosDetJSON
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:consultarInventariosDetJSON } 

MinSalSCAProcesosBundle_mantInventarioDetEdicion:
    pattern:  /inventario/mantInventarioDetEdicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantInventarioDetEdicion }

MinSalSCAProcesosBundle_mantCargarInventarioDet:
    pattern:  /inventario/mantCargarInventarioDet/{invDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantCargarInventarioDet } 
    
    
#*****************************
#*** Solicitud Importacion ***
#*****************************
MinSalSCAProcesosBundle_mantSolImportacionIngreso:
    pattern:  /Solicitud/Importacion/Ingreso
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionIngreso } 
    
MinSalSCAProcesosBundle_consultarSolImportacionDetJSON:
    pattern:  /Solicitud/Importacion/Consultar/{etpId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:consultarSolImportacionJSON } 

MinSalSCAProcesosBundle_mantSolImportacionEdicion:
    pattern:  /Solicitud/Importacion/Edicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionEdicion }

MinSalSCAProcesosBundle_mantCargarSolImportacion:
    pattern:  /Solicitud/Importacion/Cargar/{impDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantCargarSolImportacion } 
    
MinSalSCAProcesosBundle_cambiarEstado:
    pattern:  /Solicitud/Importacion/CambiarEstado/{solImpId}/{traId}/update
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:cambiarEstado }

MinSalSCAProcesosBundle_getCuotas:
    pattern:  /Solicitud/Importacion/getCuotas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getCuotas }