#****************************
#*** Inventario Detallado ***
#****************************
MinSalSCAProcesosBundle_mantInventariosDet:
    pattern:  /inventario/mantInventariosDet
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantInventariosDet } 
    
MinSalSCAProcesosBundle_consultarInventariosDetJSON:
    pattern:  /inventario/consultarInventariosDetJSON
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:consultarInventariosDetJSON } 

MinSalSCAProcesosBundle_mantInventarioDetEdicion:
    pattern:  /inventario/mantInventarioDetEdicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantInventarioDetEdicion }

MinSalSCAProcesosBundle_mantCargarInventarioDet:
    pattern:  /inventario/mantCargarInventarioDet/{invDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantCargarInventarioDet } 
    
    
#*****************************
#*** Solicitud Importacion ***
#*****************************
MinSalSCAProcesosBundle_mantSolImportacionIngreso:
    pattern:  /Solicitud/Importacion/Ingreso
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionIngreso } 
    
MinSalSCAProcesosBundle_consultarSolImportacionDetJSON:
    pattern:  /Solicitud/Importacion/Consultar/{etpId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:consultarSolImportacionJSON } 

MinSalSCAProcesosBundle_mantSolImportacionEdicion:
    pattern:  /Solicitud/Importacion/Edicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionEdicion }

MinSalSCAProcesosBundle_mantCargarSolImportacion:
    pattern:  /Solicitud/Importacion/Cargar/{impDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantCargarSolImportacion } 
    
MinSalSCAProcesosBundle_cambiarEstado:
    pattern:  /Solicitud/Importacion/CambiarEstado/{impDetId}/{traId}/update
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:cambiarEstado }

MinSalSCAProcesosBundle_getCuotas:
    pattern:  /Solicitud/Importacion/getCuotas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getCuotas }

#Visualizacion de solicitudes de importacion por empresa
MinSalSCAProcesosBundle_mantSolImportacionVerSolicitudes:
    pattern:  /Solicitud/Importacion/VerSolicitudes
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionVerSolicitudes } 
    
MinSalSCAProcesosBundle_verSolImportacionesJSON:
    pattern:  /Solicitud/Importacion/VerSolicitudes/Consultar
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:verSolImportacionesJSON } 

MinSalSCAProcesosBundle_getSearchEstados:
    pattern:  /Solicitud/Importacion/getSearchEstados 
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getSearchEstados }

MinSalSCAProcesosBundle_getSearchEtapas:
    pattern:  /Solicitud/Importacion/getSearchEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getSearchEtapas }
    
    
MinSalSCAProcesosBundle_mantSolImportacionVerSolicitudesMINSAL:
    pattern:  /Solicitud/Importacion/VerSolicitudes/{etpEntidad}/
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionVerSolicitudes, etpEntidad: 'MINSAL'}
    
MinSalSCAProcesosBundle_getEtapas:
    pattern:  /Solicitud/Importacion/getEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getEtapas }



#*****************************
#***    Solicitud Local    ***
#*****************************
MinSalSCAProcesosBundle_mantSolLocalIngreso:
    pattern:  /Solicitud/Local/Ingreso
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantSolLocalIngreso }
    
MinSalSCAProcesosBundle_consultarSolLocalDetJSON:
    pattern:  /Solicitud/Local/Consultar/{etpId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:consultarSolLocalJSON }

MinSalSCAProcesosBundle_mantSolLocalEdicion:
    pattern:  /Solicitud/Local/Edicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantSolLocalEdicion }

MinSalSCAProcesosBundle_mantCargarSolLocal:
    pattern:  /Solicitud/Local/Cargar/{localDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantCargarSolLocal }
    
MinSalSCAProcesosBundle_cambiarEstado:
    pattern:  /Solicitud/Local/CambiarEstado/{localDetId}/{traId}/update
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:cambiarEstado }

MinSalSCAProcesosBundle_getCuotas:
    pattern:  /Solicitud/Local/getCuotas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getCuotas }

MinSalSCAProcesosBundle_getProveedores:
    pattern:  /Solicitud/Local/getProveedores
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getProveedores }

#Visualizacion de solicitudes Locales por empresa
MinSalSCAProcesosBundle_mantSolLocalVerSolicitudes:
    pattern:  /Solicitud/Local/VerSolicitudes
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantSolLocalVerSolicitudes } 
    
MinSalSCAProcesosBundle_verSolLocalesJSON:
    pattern:  /Solicitud/Local/VerSolicitudes/Consultar
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:verSolLocalesJSON } 

MinSalSCAProcesosBundle_getSearchEstados:
    pattern:  /Solicitud/Local/getSearchEstados 
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getSearchEstados }

MinSalSCAProcesosBundle_getSearchEtapas:
    pattern:  /Solicitud/Local/getSearchEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getSearchEtapas }
    
    
MinSalSCAProcesosBundle_mantSolLocalVerSolicitudesMINSAL:
    pattern:  /Solicitud/Local/VerSolicitudes/{etpEntidad}/
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantSolLocalVerSolicitudes, etpEntidad: 'MINSAL'}
    
MinSalSCAProcesosBundle_getEtapas:
    pattern:  /Solicitud/Local/getEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getEtapas }